### ISSUE TITLE
implement base fare (and minimum fare)

### ISSUE THREAD

**Issue by tschlenther** [eqasim-org/matsim-sharing#6]
Hi @balacmi, thanks for implementing service fares! We were actually doing the same thing at the same time but it is much cleaner if the matsim-sharing module takes care of it itself. I have one feature request, though:
It looks like you have implemented distance and time based fare compononents, only. However, many services charge something like a base fare and some may even also have something like a minimum fare. We have accounted for this in the DrtFareHandler as well, if you want to have a place for lookups. Would you be able to implement these fare components as well?
Thank you really much!

**Comment by balacmi** [comment]
Hi @tschlenther , thank you for pointing this out. It was on my TODO list, but I got distracted by something else. I will take care of it most probably tomorrow or latest in 2 days.

**Comment by tschlenther** [comment]
Thank you :)
